// Contains constants for all action types

//Character Actions
export const LOAD_CHARACTERS_SUCCESS = 'LOAD_CHARACTERS_SUCCESS';
export const CREATE_CHARACTER_SUCCESS = 'CREATE_CHARACTER_SUCCESS';
export const UPDATE_CHARACTER_SUCCESS = 'UPDATE_CHARACTER_SUCCESS';

//Tracker Actions
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
export const INCREMENT_CHAR_LIST = 'INCREMENT_CHAR_LIST';
export const DECREMENT_CHAR_LIST = 'DECREMENT_CHAR_LIST';

//Ajax Actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';