// Contains constants for all action types

//Character Actions
export const LOAD_CHARACTERS_SUCCESS = 'LOAD_CHARACTERS_SUCCESS';
export const CREATE_CHARACTER_SUCCESS = 'CREATE_CHARACTER_SUCCESS';
export const UPDATE_CHARACTER_SUCCESS = 'UPDATE_CHARACTER_SUCCESS';

//INITIATIVE Actions
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
export const INCREMENT_INITIATIVE_LIST = 'INCREMENT_INITIATIVE_LIST';
export const DECREMENT_INITIATIVE_LIST = 'DECREMENT_INITIATIVE_LIST';
export const CALCULATE_PROGRESS = 'CALCULATE_PROGRESS';
export const RESET_INDEX = 'RESET_INDEX';
export const UPDATE_TURN_COUNT = 'UPDATE_TURN_COUNT';

//Ajax Actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';